server:
  port: 8080

spring:
  application:
    name: assembly-voting
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: voting-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      session:
        timeout:
          ms: 30000
      request:
        timeout:
          ms: 30000

spring-doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /
    disable-swagger-default-url: false

# Opções de configuração para a aplicação de votação
session-settings:
  # Tempo de duração de uma sessão de votação em segundos
  life-time: 60

  # Opções para enviar mensagem ao finalizar uma sessão de votação
  post-result-on-end: true

  # Intervalo de tempo para atualizar a sessão de votação em segundos
  update-rate: 25

  # Verificar se o CPF do associado é válido antes de votar
  validate-cpf: false

  #  Por algum motivo o endpoint de validação de CPF não está funcionando
  #  então foi criado um endpoint local para simular a validação
  endpoint-url: "https://user-info.herokuapp.com/users"